
const PrivacyPolicy = () => {
    return (
        <>
            <div style={{margin: "60px", marginTop: "40px"}}>
                <p style={{textAlign: "center", fontSize: 36}}>Privacy Policy</p>

                <p className="mt-4" style={{fontWeight: 600}}>Effective Date: [insert date posted]</p>
                <p className="mt-4">SuperMind AI, Inc. (“<b>SuperMind AI</b>,” “<b>we</b>,” “<b>us</b>,” or “<b>our</b>”) provides the SuperMind website, chrome extension, and related AI tools, resources, content, and features (collectively, “<b>SuperMind</b>”). Regarding your interaction with SuperMind – whether as an AI assistant (bot) creator or a buyer – this Privacy Policy (this “<b>Policy</b>”) applies to you. This Policy describes the information we collect, including how we collect it, how we use it, who we share it with, and other related information about our privacy practices. </p>
                <p className="mt-4">Please review and agree to this Policy (and our Terms of Service) before creating an account and developing or buying AI assistants (bots). By creating an account and interacting with SuperMind, you consent to this Policy. If you do not consent to this Policy, please do not use SuperMind. </p>

                <p className="mt-4" style={{fontSize: 24, fontWeight: 700}}>Who We Are; Contact Information</p>
                <p>SuperMind, AI, Inc. operates SuperMind, including the website, website extension, and all associated services and tools. We are a company registered in Delaware and operating from the State of New York. We are responsible for collecting and handling your information in connection with SuperMind. </p>
                <p className="mt-4">If you have any questions, inquiries, complaints, reviews, or feedback regarding this Policy, please get in touch with us using the Contact Us section of our website or by using the company information below: </p>
                <div className="mt-4">SuperMind, AI, Inc</div>
                <a href="mailto:admin@supermind.bot">admin@supermind.bot</a>

                <p className="mt-4" style={{fontSize: 24, fontWeight: 700}}>Information Collection</p>
                <p>We collect the information that allows us to provide SuperMind, authenticate you, improve SuperMind, comply with the law, and secure SuperMind. The information we collect may include the following: </p>
                <ul className="mt-4 ms-4">
                    <div><b>•	Account information:</b> We collect information when you create a user account on our website. The information we collect includes your full name, email address, phone number, and login credentials. </div>
                    <div className="mt-4"><b>•	Social media information:</b> If you use the Google sign-in feature to create or sign in to your account, we will obtain your Google profile information and use it to create an account or seamlessly enable your access to SuperMind. The information we collect from your Google account includes your name and email address. You can revoke access to your Google information by logging into your Google permission settings. Your Google account and the information you have on it are governed by the privacy policy of Google, Inc., which can be found <a href="https://policies.google.com/privacy?hl=en-US">here</a>. </div>
                    <div className="mt-4"><b>•	Communication information:</b> We collect information needed to establish communication with you. This may include your email address and phone number. We collect this information when you contact us, subscribe to our newsletter, create account, or submit order information. </div>
                    <div className="mt-4"><b>•	Content information:</b> We collect any information you share when you post content on our website, including when you submit reviews and feedback after purchasing an AI assistant (bot) or completing your profile bio. Your review may include your name and may be publicly available to other users of SuperMind. </div>
                    <div className="mt-4"><b>•	Purchase or order information:</b> We collect any information associated with your purchase of any AI assistant on SuperMind. This may include your credit/debit card and billing information, as well as the amount paid, timestamp, product purchased, and payment method used.</div>
                </ul>
                <p className="mt-4">You are under no obligation to provide us with the information above. However, the provision of SuperMind according to your use depends on this information. Therefore, we are unable to offer you the tools and resources to create and sell your bots or purchase them without providing the required information. </p>
                <p className="mt-4">Also, some of the information (for example, your credit/debit card details) may be regarded as “sensitive information” under certain laws. By providing such information, you consent to us using it for the purpose described. Nevertheless, we employ additional safeguards for such information (for example, we do not store your payment method (credit/debit) information on our database. They are provided to and used by Stripe to process your payments or withdrawals.  </p>

                <p className="mt-4" style={{fontSize: 24, fontWeight: 700}}>Information Uses</p>
                <p>In summary, we collect the information above primarily to provide you with the resources offered through SuperMind, communicate with you, and comply with applicable laws and regulations. </p>
                <p className="mt-4">In detail, we collect your information for the following purposes: </p>
                <ul className="mt-4 ms-4">
                    <div>•	Authentication and account management: We collect registration information to authenticate you and allow you to manage your account and profile. We also collect your social media information to provide you with seamless access to an account. </div>
                    <div className="mt-4">•	Communication purposes: We collect your email address and phone number to communicate with you, provide support, respond to your inquiries, and send marketing emails based on your consent. </div>
                    <div className="mt-4">•	Payment processing: We collect payment method information to enable us (through Stripe) to charge you for any purchases or credit you for any sales made as an AI assistant developer. This includes Points in your account wallet. </div>
                    <div className="mt-4">•	Legal compliance: We may collect some information, such as transaction details, to comply with the law and keep records for future purposes. </div>
                    <div className="mt-4">•	Security and fraud prevention: We collect some information to secure SuperMind and monitor activities relating to fraud. </div>
                    <div className="mt-4">•	Product improvement: We collect your feedback and review to enable us to identify and improve our bots or add features to them. </div>
                </ul>

                <p className="mt-4" style={{fontSize: 24, fontWeight: 700}}>Legal Basis for Processing Information</p>
                <p>Under applicable data protection laws, we are required to inform you of the legal basis on which we process your information. The legal basis for processing your information may vary depending on the specific circumstances and purposes for which we collect and use your information. The following are the legal bases for processing information that we rely on:</p>
                <ul className="mt-4 ms-4">
                    <div>-	<b>Consent:</b> In most cases, we may process your information based on your explicit consent. For example, we may seek your consent before sending you marketing emails. You can withdraw your consent at any time where consent is the basis for processing any of your information. </div>
                    <div className="mt-4">-	<b>Contractual Necessity:</b> We may process your information to fulfill our contractual obligations to you or to take pre-contractual steps at your request. For example, we may process your payment information to complete a purchase or provide you with the AI (bot) you have requested.</div>
                    <div className="mt-4">-	<b>Legal Obligations:</b> We may process certain information to comply with legal obligations or regulatory requirements to which we are subject. For example, we may process your information for tax compliance, fraud prevention, or responding to lawful requests from law enforcement or government authorities.</div>
                </ul>

                <p className="mt-4" style={{fontSize: 24, fontWeight: 700}}>Cookies and Tracking</p>
                <p>We and third-party service providers may use cookies, beacons, and similar technologies to run and secure our website and extension. Cookies are small text files that are placed on your device (computer, smartphone, or tablet) when you visit a website. They are widely used to enable the website’s functionality and enhance user experience. </p>
                <p className="mt-4">We use the cookies that are necessary and essential for the operation of our website and enable core functionalities such as session management, authentication, and security. We use session cookies to maintain your session and persistent cookies with a lifespan of 2 hours to remember your preferences and settings during your visit.</p>
                <p className="mt-4">As mentioned above, our third-party service providers (such as our authentication and payment processing partners) may set their own cookies to perform their services for us. </p>
                <p className="mt-4">Cookies are either “session” or “persistent” in terms of how long they remain on your device. While session cookies expire immediately you close your browser after a session, persistent cookies may extend for longer periods according to their set expiration dates. </p>
                <p className="mt-4">Most web browsers allow you to control cookies through their privacy settings. You can typically set your browser to block or delete cookies, or to alert you when cookies are being sent. However, please note that blocking or deleting cookies may affect the functionality of our website and may prevent you from accessing certain features.</p>

                <p className="mt-4" style={{fontSize: 24, fontWeight: 700}}>Information Disclosure </p>
                <p>We do not sell or share information about users other than as described below:</p>
                <ul className="mt-4 ms-4">
                    <div><b>•	Information shared with third-party service providers:</b> We work with certain third parties to provide SuperMind. This may include sharing your payment method information with Stripe to process your payments. The sharing of information with these third parties is consistent with this Policy. Third-party service providers are under obligation to only use your information for the services they render on our behalf. </div>
                    <div className="mt-4"><b>•	Information shared with law enforcement:</b> We may disclose your personal information if required to do so by law or in response to valid legal requests, such as subpoenas, court orders, or government regulations. We may also disclose your information to protect our rights, property, or safety, or the rights, property, or safety of other users and third parties.</div>
                    <div className="mt-4"><b>•	Information shared with other entities in a business transfer transaction:</b> In the event of a merger, acquisition, asset sale, or other business transaction involving SuperMind AI, your personal information may be transferred to the acquiring entity or successor organization as part of the transaction. We will notify you via email or prominent notice on our website of any such change in ownership or control of your personal information.</div>
                    <div className="mt-4"><b>•	Information shared with your consent:</b> We may share your personal information with third parties for purposes not described in this Policy or as otherwise disclosed to you at the time of collection, provided that we obtain your consent to do so.</div>
                </ul>
                <div className="mt-4" style={{fontWeight: 600}}>Information transferred outside of your location</div>
                <p>Although SuperMind is operated from the United States (US), be aware that information about you may be processed and transferred to locations outside of your location and the US. However, we ensure the entity we transfer information to in a different country complies with the same privacy as this Policy. </p>
                <p className="mt-4">We carry out all transfers in accordance with all applicable laws. For example, if the transfer is from the EEA, EU, UK, and similar locations under the General Data Protection Regulation (GDPR) or similar laws, we use approved transfer measures, such as the Standard Contractual Clauses. </p>

                <p className="mt-4" style={{fontSize: 24, fontWeight: 700}}>Security of Information</p>
                <p>We take the security of your personal information seriously and have implemented appropriate technical and organizational measures to protect your data from unauthorized access, disclosure, alteration, and destruction. </p>
                <p className="mt-4">We use industry-standard encryption protocols, such as SSL, to encrypt data transmitted between your browser and our website to prevent unauthorized interception of your personal information during transmission.</p>
                <p className="mt-4">Your personal information is stored on secure servers with restricted access controls to prevent unauthorized access or tampering. We regularly review and update our security measures to ensure the integrity and confidentiality of your information.</p>
                <p className="mt-4">Access to personal information is restricted to authorized personnel with a legitimate need to access such information for the purposes described in this Policy. We enforce strict access controls and authentication mechanisms to prevent unauthorized access to personal information.</p>
                <p className="mt-4">However, while we take reasonable precautions to protect personal information, you are aware that no method of transmission over the Internet or method of electronic storage is completely secure. Therefore, we cannot guarantee the absolute security of your information. By using SuperMind and providing us with your information, you acknowledge and accept the inherent risks associated with data transmission and storage.</p>

                <p className="mt-4" style={{fontSize: 24, fontWeight: 700}}>Information Retention</p>
                <p>We retain the information we hold about users for as long as their account is active. If you choose to deactivate your account or request a deletion of your information (or we close your account after some months of inactivity), we act on your request and delete your information within 30 days of your request. This allows us to reactivate your account in case you change your mind or make the request accidentally. It also helps us with audit, tax, accounting, and compliance with applicable laws. We may be required to retain personal information for longer periods to comply with our legal obligations, resolve disputes, prevent any legal claims, and enforce our Terms of Service. In that case, the information will be retained for the duration required by law. </p>

                <p className="mt-4" style={{fontSize: 24, fontWeight: 700}}>User Privacy Rights </p>
                <p>Your location law provides you with some or all of the following rights regarding your information: </p>
                <ul className="mt-4 ms-4">
                    <div><b>•	Right to access:</b> You have the right to request access to the personal information we hold about you and to receive a copy of that information. Upon request, we will provide you with information about whether we hold any of your personal information and, if so, the categories of personal data, the purposes of processing, and the recipients or categories of recipients to whom the personal information has been or will be disclosed. You can make this request via <a href="mailto:admin@supermind.bot">admin@supermind.bot</a>. </div>
                    <div className="mt-4"><b>•	Right to rectification:</b> If you believe that any personal information we hold about you is inaccurate, incomplete, or outdated, you have the right to request that we correct or update your information. You may also request that we restrict the processing of your personal data while we verify its accuracy. You can correct any information via your account dashboard.</div>
                    <div className="mt-4"><b>•	Right to erasure:</b> You have the right to request the deletion of your personal information under certain circumstances, such as when the data is no longer necessary for the purposes for which it was collected, when you withdraw your consent (if consent is the legal basis for processing), or when you object to the processing and there are no overriding legitimate grounds for the processing. You can request erasure by using the account deletion function under your profile or by emailing us at <a href="mailto:admin@supermind.bot">admin@supermind.bot</a>. </div>
                    <div className="mt-4"><b>•	Right to restrict processing:</b> You have the right to request the restriction of processing of your personal information under certain circumstances, such as when you contest the accuracy of the information, when the processing is unlawful, or when you have objected to processing pending the verification of legitimate grounds. Email us at <a href="mailto:admin@supermind.bot">admin@supermind.bot</a> to exercise this right. </div>
                    <div className="mt-4"><b>•	Right to data portability:</b> You have the right to receive your personal information in a structured, commonly used, and machine-readable format and to transmit that data to another service provider without hindrance, where technically feasible. Email us at <a href="mailto:admin@supermind.bot">admin@supermind.bot</a> to exercise this right. </div>
                    <div className="mt-4"><b>•	Right to withdraw consent:</b> If we are processing your information based on your consent, you have the right to withdraw that consent at any time (for example, you can opt out of email newsletters at any time by using the unsubscribe button at the bottom of any email we send to you). Withdrawal of consent will not affect the lawfulness of processing based on consent before its withdrawal.</div>
                    <div className="mt-4"><b>•	Right to lodge a complaint:</b> If you believe that we have infringed upon your privacy rights or violated applicable data protection laws, you have the right to lodge a complaint with the relevant supervisory authority in your jurisdiction.</div>
                </ul>
                <p className="mt-4">Please note that certain rights may be subject to limitations or exceptions under applicable laws, and we may need to verify your identity before processing your request. Additionally, we may retain certain information as required or permitted by law, such as for legal or compliance purposes, to resolve disputes, or to enforce our rights.</p>

                <p className="mt-4" style={{fontSize: 24, fontWeight: 700}}>Children's Policy</p>
                <p>SuperMind is targeted at individuals who are at least 18 years of age. We do not knowingly collect personal information from people under 18 years of age (without parental consent). If we become aware that we have inadvertently collected personal information from a child without parental consent, we will promptly delete such information from our records. By using SuperMind, you represent that you are at least 18. </p>
                <p className="mt-4">If you are a parent or legal guardian whose child has submitted personal information to us, you can request it deleted from our records. You can send your deletion request to <a href="mailto:admin@supermind.bot">admin@supermind.bot</a>. </p>

                <p className="mt-4" style={{fontSize: 24, fontWeight: 700}}>Do Not Track</p>
                <p>Do Not Track is a website privacy feature that, when activated, sends a notice to us to stop tracking your activities across our website and extension. An applicable law requires that we let you know if we respond to Do Not Track signals from your browser. Due to the inconsistency of this feature among industry participants, we do not respond to the Do Not Track signal. Also, we do not track your use of SuperMind at this time. </p>

                <p className="mt-4" style={{fontSize: 24, fontWeight: 700}}>Third-Party Services</p>
                <p>Some parts of the SuperMind website and browser extension may contain content and links to third-party websites and services that are not owned or controlled by SuperMind, AI. These third-party links or content exist on SuperMind for reference and convenience purposes and are not governed by this Policy. When you connect to a third-party website or service and provide them with information, their privacy policies will govern. Please ensure you read them. We are not responsible for any loss of information related to your use of a third-party website, service, or content. </p>

                <p className="mt-4" style={{fontSize: 24, fontWeight: 700}}>Changes to this Policy</p>
                <p>We may update this Policy to reflect changes in our practices or applicable privacy laws. Users will be notified of any significant changes via their email addresses, or by a display on the SuperMind website or your dashbboard. The updated Policy will be effective upon posting it. By your continued use of SuperMind after any changes to this Policy, you are deemed to have consented to the changes made. </p>
            </div>
        </>
    )
}

export default PrivacyPolicy;